// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"missCommon","status":true,"description":"","parameters":{}},
{"name":"BeforeCommon","status":true,"description":"ver1.01/スキルやアイテムの発動前に、スキルやアイテムに設定されたコモンイベントを発生させます。","parameters":{"IndexVariableID":"1","TargetIndexVariableID":"12"}}
];
