// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"InsertOpeningMap","status":true,"description":"タイトル前にOPを挿入するプラグイン","parameters":{"mapId":"2","canSkip":"true","playerPos":"{\"X\":\"17\",\"Y\":\"36\"}","isTrans":"true","isValidOp":"false","isShowFlw":"false"}}
];
